#!/bin/bash
cmd="$HOME/.leovim.unix/linux/tokei ./ rtp/leo -e conf.d/main/autoload/plug.vim rtp fonts scripts assets .gits *.md *.sh *.cmd LICENSE tokei"
cd ~/.leovim
if [ $# == 1 ] && [ $1 == 'all' ]; then
    $cmd --files 
    $cmd
else
    echo -e "==== \e[33mNOTE\e[0m: Add parameter \e[31mall\e[0m after command \e[32mtokei\e[0m to show details of each file ===="
    $cmd
fi
