#!/bin/bash
cmd="$HOME/.leovim.unix/linux/tokei ./conf.d -e conf.d/main/autoload/plug.vim *.md *.sh *.cmd"
cd ~/.leovim
if [ $# == 1 ] && [ $1 == 'all' ]; then
    $cmd --files 
    $cmd
else
    echo -e "==== \e[33mNOTE\e[0m: Add parameter \e[31mall\e[0m after command \e[32mtokei\e[0m to show details of each file ===="
    $cmd
fi
