#!/bin/bash
cmd="$HOME/.leovim.unix/linux/tokei ./ pack/leo -e config/autoload/plug.vim pack fonts .git LICENSE scripts/* *.md *.sh *.cmd tokei"
cd ~/.leovim
if [ $# == 1 ] && [ $1 == 'all' ]; then
    $cmd --files 
    $cmd
else
    echo -e "==== \e[33mNOTE\e[0m: Add parameter \e[31mall\e[0m after command \e[32mtokei\e[0m to show details of each file ===="
    $cmd
fi
