vim.keymap.set({ "n", "x" }, '+', function() return require("opencode").operator("@this ") end, { desc = "Add range to opencode", expr = true })
vim.keymap.set({ "n", "x" }, "<Tab>ol", function() require("opencode").ask("@this: ", { submit = true }) end, { desc = "Ask opencode this" })
vim.keymap.set({ "n", "x" }, "<Tab>of", function() require("opencode").ask("@buffer: ", { submit = true }) end, { desc = "Ask opencode buffer" })
vim.keymap.set({ "n", "x" }, "<Tab>od", function() require("opencode").ask("@diagnositcs: ", { submit = true }) end, { desc = "Ask opencode diagnositcs" })
vim.keymap.set({ "n", "x" }, "<Tab>ov", function() require("opencode").ask("@visible: ", { submit = true }) end, { desc = "Ask opencode visible" })
vim.keymap.set({ "n", "x" }, "<Tab>ob", function() require("opencode").ask("@buffers: ", { submit = true }) end, { desc = "Ask opencode buffers" })
vim.keymap.set({ "n", "x" }, "<Tab>oq", function() require("opencode").ask("@quickfix: ", { submit = true }) end, { desc = "Ask opencode quickfix" })
vim.keymap.set({ "n", "x" }, "<Tab>og", function() require("opencode").ask("@diff: ", { submit = true }) end, { desc = "Ask opencode gdiff" })
vim.keymap.set({ "n", "x" }, "<Tab>om", function() require("opencode").ask("@marks: ", { submit = true }) end, { desc = "Ask opencode marks" })
vim.keymap.set({ "n", "x" }, "<Tab>oe", function() require("opencode").select() end, { desc = "Execute opencode action…" })
vim.keymap.set({ "n", "t" }, "<M-e>o", function() require("opencode").toggle() end, { desc = "Toggle opencode" })
